name = "pg_value"
version = "2.0.0"
description = "Gleam library providing Postgres data types, encoders, and decoders"
licences = ["MIT"]
repository = { type = "github", user = "stndrs", repo = "pg_value" }

[dependencies]
gleam_stdlib = ">= 0.44.0 and < 2.0.0"
gleam_time = ">= 1.6.0 and < 2.0.0"

[dev-dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"
